services:
  prometheus:
    image: prom/prometheus:v3.5.1
    ports:
      - 9090:9090
    volumes:
      - /root/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/monitoring/prometheus:/prometheus
  grafana:
    image: grafana/grafana:12.4.0-22046043985
    ports:
      - 3000:3000
    volumes:
      - /root/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
      - /root/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - /var/monitoring/grafana:/var/lib/grafana